// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwsunqlxehadmqikkdhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3c3VucWx4ZWhhZG1xaWtrZGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMjI2NzksImV4cCI6MjA1Njc5ODY3OX0.FiX_3gmWRNPCvdhiEtEwoN43PRcKD_7yIn8ZM5Yykpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);